### ISSUE TITLE
README.md basic example visualization issue

### ISSUE THREAD

**Issue by Petr-A** [POVME/POVME#30]
In examples directory (in the README.md file) under basic example, it reads:

`vmd -m POVME_test_run/POVME_volume_trajectory.pdb 1BYQ_every250.pdb`

When I run that, I get: 
ERROR) Could not read file POVME_test_run/POVME_volume_trajectory.pdb
ERROR) Loading of startup molecule files aborted.

I noticed that if I run:
`vmd -m POVME_test_run/example_volume_trajectory.pdb 4NSS.pdb`
It loads without error and gives a model that appears to make sense (corresponds to what I think the sample_input.ini code would produce).

Also, when I completed the ligand-defined inclusion region example, I used the first vmd code to see the output, which worked for that example.

**Comment by j-wags** [comment]
Thanks for the correction, @Petr-A! PR #31 updates the README with fixes.

In the interest of transparency, I'm only able to devote a fraction of my free time to maintaining this project. I hope you have a good experience using it, but it's unlikely that I'll be able to provide significant support if users encounter technical issues. I'd be happy to review and accept PRs, and invite interested parties to be POVME organization members (with edit rights).

I've become a better developer since I made POVME 3.0, so I can see the serious deficiencies in this software. But (unfortunately?), becoming more skilled has made it important that I devote my finite effort to [drive broader community efforts](openforcefield.org). If there's serious interest, I could work on updating POVME3.0 to [a more maintainable format](https://github.com/MolSSI/cookiecutter-cms), but I'd like to see some indication of significant community interest before I devote tens of hours to an overhaul.

**Comment by Petr-A** [comment]
Thanks for your email-- I'm glad the suggestion was helpful.

While I understand that looking back on POVME 3.0 development you see some
things you would do differently now, the program is very helpful as is. If
the projects we are using it for unfold as hoped, I will be sure to credit
your work. Thanks for letting me know that it is not your primary project
at the moment. If while using POVME we generate ideas for an update, I'll
keep in mind the ideas you mentioned. Thank you for the time you put
towards generating this nice program.

Cheers,
Anna
