### ISSUE TITLE
Get volume and poc

### ISSUE THREAD

**Issue by pgbarletta** [POVME/POVME#32]
I noticed POVME3 is running much slower than POVME2 and is outputting much more data. Is there an option to cancel all those extra features and only getting the cavity PDB an the `prefix_output.txt` file with the volume of each frame?

Thanks!

**Comment by j-wags** [comment]
Apologies for the long delay. Unfortunately, POVME3 doesn't have a way to turn off the new features. It has a "more is more" philosophy, which I have since learned is not necessarily a good design pattern. 

For a volume-only running mode, you might consider using POVME2, which is still being maintained: https://git.durrantlab.pitt.edu/jdurrant/POVME
